version: '3'

services:
  mariadb-server:
    build: https://5c120b6eb6dc4b7b2fed61ce03f1dbb834aaf55c@github.com/millenium9977/seminar-databases-and-express.git#typeorm:my-movie-db-backend
    expose:
    - "3000"
    ports:
    - 3000:3000
    networks:
    - mariadb-network
    environment:
      - PORT=3000
      - MARIA_USER=seminar
      - MARIA_PASSWORD=seminar
      - MARIA_PORT=3306
      - MARIA_HOST=mariadb-database
      - RETRY_TIMEOUT=10000
    depends_on:
      - mariadb-database

  mariadb-database:
    image: mariadb:latest
    ports:
      - 3305:3306
    networks:
    - mariadb-network
    restart: always
    volumes:
    - mariadb-database:/mdbdata/mariadb-database
    environment:
      - MYSQL_ROOT_PASSWORD=seminar
      - MYSQL_USER=seminar
      - MYSQL_PASSWORD=seminar
      - MYSQL_DATABASE=moviedb

volumes:
  mariadb-database:


networks:
  mariadb-network:
    driver: bridge
  neo4j-network:
    driver: bridge
  mongodb-network:
    driver: bridge
